Update to 1.18.2
PotatoPresident/Fedora pull request #19
Opened 2022-03-19 18:12 UTC by byquanton

- Update to 1.16.5
- Update to 1.18.2

2022-03-22 00:55 UTC, PotatoPresident requested changes
Looks good!
Only things I noticed is that the github actions need to be updated to latest java and offsets need to be added for the new mobs in `FedoraClient$registerVanillaHelpers`

2022-03-22 17:26 UTC, byquanton commented
https://user-images.githubusercontent.com/32410361/159539831-23dea6e4-20da-4ebf-98c8-ddaa466d04d6.mp4

2022-03-25 15:40 UTC, PotatoPresident approved these changes

2022-03-29 05:09 UTC, byquanton commented
Merge, or is there anything left to-do?

2022-03-31 18:10 UTC, merged